### ISSUE TITLE
bitwise operators might be a nice addition

### ISSUE THREAD

**Issue by dlrobertson** [mmaechler/R-bitops#2]
As a C/C++ programmer the bitwise operators might be a nice addition

E.g

```
    `%<<%` <- function(x, y) { return(bitShiftL(x, y)) }
```

**Comment by mmaechler** [comment]
well, more nicely  (R is _not_ C ..}

```
    `%<<%` <- function(x, y) bitShiftL(x, y)
```

Yeah that may be nice  for those who are used to that notation.
Are you interested enough to provide a pull request?

**Comment by dlrobertson** [comment]
> well, more nicely (R is not C ..}
> 
> ```
>    `%<<%` <- function(x, y) bitShiftL(x, y)
> ```

Very true! Still working on that.

> Are you interested enough to provide a pull request?

Sure! I'll see what I can do.

**Comment by mmaechler** [comment]
... I am still waiting for your PR @danlrobertson ..
